- name: Install telnet
  yum:
    name=telnet
    state=present
- name: install one specific version of Apache
  yum:
    name: httpd-"{{ hostvars[groups['tag_env_prod'][0]]['httpd_version'] }}".amzn1
    state: present
