---
- name: install and configure postgresl
  hosts: tag_Name_dev_postgresql_instance
  become: yes
  vars:
    max_connections: "{{ hostvars[groups['tag_env_dev'][0]]['postgresql_max_connections'] }}"
    db_users:
      - name: admin
        role_attr_flags: SUPERUSER
      - name: service1
      - name: user1
      - name: user2

  roles:
    - postgresql
